export const MainChannels = [
  "main:session:create",
  "main:session:read",
  "main:session:update",
  "main:session:delete",
  "main:session:list",
  "main:event:create",
  "main:event:read",
  "main:event:update",
  "main:event:delete",
  "main:event:list",
  "main:discipline:create",
  "main:discipline:read",
  "main:discipline:update",
  "main:discipline:delete",
  "main:discipline:list",
];
export const PerfomanceSportsChannels = [
  "ps:event:create",
  "ps:event:read",
  "ps:event:update",
  "ps:event:delete",
  "ps:event:list",
  "ps:house:create",
  "ps:house:read",
  "ps:house:update",
  "ps:house:delete",
  "ps:house:list",
  "ps:participant:create",
  "ps:participant:read",
  "ps:participant:update",
  "ps:participant:delete",
  "ps:participant:list",
];
export const TeamSportsChannels = [
  // Team
  "ts:team:create",
  "ts:team:read",
  "ts:team:update",
  "ts:team:delete",
  "ts:team:list",
  // Player
  "ts:player:create",
  "ts:player:read",
  "ts:player:update",
  "ts:player:delete",
  "ts:player:list",
  // Fixture
  "ts:fixture:create",
  "ts:fixture:read",
  "ts:fixture:update",
  "ts:fixture:delete",
  "ts:fixture:list",
  // Fixture Event
  "ts:fixture_event:create",
  "ts:fixture_event:read",
  "ts:fixture_event:update",
  "ts:fixture_event:delete",
  "ts:fixture_event:list",
  // Fixture Participant
  "ts:fixture_participant:create",
  "ts:fixture_participant:read",
  "ts:fixture_participant:update",
  "ts:fixture_participant:delete",
  "ts:fixture_participant:list",
  // Player Fixture Stats
  "ts:player_fixture_stats:create",
  "ts:player_fixture_stats:read",
  "ts:player_fixture_stats:update",
  "ts:player_fixture_stats:delete",
  "ts:player_fixture_stats:list",
];
export const TournamentChannels = [
      "tournament:team:create",
      "tournament:team:read",
      "tournament:team:update",
      "tournament:team:delete",
      "tournament:team:list",
      "tournament:player:create",
      "tournament:player:read",
      "tournament:player:update",
      "tournament:player:delete",
      "tournament:player:list",
      "tournament:group:create",
      "tournament:group:read",
      "tournament:group:update",
      "tournament:group:delete",
      "tournament:group:list",
      "tournament:group_team:create",
      "tournament:group_team:read",
      "tournament:group_team:update",
      "tournament:group_team:delete",
      "tournament:group_team:list",
      "tournament:round:create",
      "tournament:round:read",
      "tournament:round:update",
      "tournament:round:delete",
      "tournament:round:list",
      "tournament:match:create",
      "tournament:match:read",
      "tournament:match:update",
      "tournament:match:delete",
      "tournament:match:list",
      "tournament:match_participant:create",
      "tournament:match_participant:read",
      "tournament:match_participant:update",
      "tournament:match_participant:delete",
      "tournament:match_participant:list",
      "tournament:player_stat:create",
      "tournament:player_stat:read",
      "tournament:player_stat:update",
      "tournament:player_stat:delete",
      "tournament:player_stat:list",
]
export const DateFormats = [
  'yyyy-MM-dd',
  'dd-MM-yyyy',
  'MM-dd-yyyy',
  'yyyy/MM/dd',
  'dd/MM/yyyy',
  'MM/dd/yyyy',
  'yyyy.MM.dd',
  'dd.MM.yyyy',
];
export const DisciplineType = ["swimming","athletics","team","tournament"]
export const IpcChannels = [
  ...MainChannels,
  ...PerfomanceSportsChannels,
  ...TeamSportsChannels,
  ...TournamentChannels
] as const;

export const natures = ["time", "height", "score", "length"] as const;
